collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /:path

title: StevenPlayzz Web

navbar-links:
  Discord: "https://discord.gg/MDfJxJZ"
#  Donate: "https://donate.teamdraco.net"

avatar: "/assets/img/favicon.png"
show-avatar: false

social-network-links:
  github: stevenplayzzdev
  twitter: stevenplayzzdev
#  patreon: stevenplayzzdev

excerpt_length: 50

feed_show_excerpt: true

feed_show_tags: true

navbar-col: "#2a1914"
navbar-text-col: "#F4F6F7"
navbar-border-col: "#3b2820"
page-col: "#c86838"
text-col: "#F4F6F7"
link-col: "#008AFF"
hover-col: "#943929"
footer-col: "#2a1914"
footer-text-col: "#F4F6F7"
footer-link-col: "#404040"

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
page-img: "/assets/img/background.png"

mobile-theme-col: "#1c385d"

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""

# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189

